### ISSUE TITLE
Firefox Compatibility

### ISSUE THREAD

**Issue by theishshah** [tanishq-dubey/cowtab#11]
Looks like this is compatible with the new version of Firefox with WebExtension support so you could submit it to the FF addon market as well

**Comment by dhaynespls** [comment]
Would it be alright if someone forked the project and submitted it themselves? I see that the LICENSE is MIT so I don't think it should be a problem as long as proper attribution is given. I'm a big fan of the extension and would like for Firefox to be supported.

**Comment by tanishq-dubey** [comment]
I've started to look at the new Firefox WebExtension method for doing this, however if you are willing @dhaynespls I do not mind forks at all (encouraged in fact)!

I'll be keeping this thread updated on my progress

**Comment by dhaynespls** [comment]
I'm quite busy at the moment actually, though I appreciate the openness to contributors.

**Comment by rungulus** [comment]
Sorry to resurrect an old issue, but I have ported the extension successfully in this PR #18  

Once approved by Mozilla, you should be able to get it on the addons store here: https://addons.mozilla.org/en-US/firefox/addon/cowtab/

Turns out to be quite easy apparently, just needed to update the manifest.json to support firefox, unsure if you can have both Firefox's and Chrome's in the same manifest file, however.

**Comment by tanishq-dubey** [comment]
Thanks for the contribution @runguszone ! I have an idea for a follow-on PR that would template out the manifest.json to build for both Firefox and Chrome.

The PR itself is pretty lightweight so I'll merge it in!
